replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/project-gcp-468607/microrepo/sample-app:${GITHUB_SHA}
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

ingress:
  enabled: false
