replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/project-gcp-468607/artirepo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}
