name: CD - deploy to GKE (staging/prod)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-gcp-468607
  CLUSTER_NAME: velath
  CLUSTER_LOCATION: us-central1-a
  NAMESPACE: production
  AR_LOCATION: us-central1
  AR_REPO: microrepo
  IMAGE_NAME: sample-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to GCP (Workload Identity)
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/237760814620/locations/global/workloadIdentityPools/github-pool/providers/github-provider' # replace
          service_account: 'github-actions-sa@project-gcp-468607.iam.gserviceaccount.com' # replace
          project_id: ${{ env.PROJECT_ID }}

      - id: getcreds
        name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_LOCATION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Deploy Helm chart
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE: ${{ env.AR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}
        run: |
          # ensure namespace exists
          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
          # helm upgrade (pass image tag so chart is immutable)
          helm upgrade --install sample-app charts/sample-app \
            --namespace $NAMESPACE \
            --set image.repository=${IMAGE} \
            --set image.tag=${IMAGE_TAG} \
            --wait --timeout 5m
