name: CI - build & push

on:
  push:
    branches: [ "main", "develop" ]
  pull_request: {}

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-gcp-468607
  AR_LOCATION: us-central1
  AR_REPO: microrepo
  IMAGE_NAME: sample-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to GCP (Workload Identity)'
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/237760814620/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@project-gcp-468607.iam.gserviceaccount.com'
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}

      - name: Login to Artifact Registry (Docker)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.AR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.AR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.AR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Set image-tag output
        id: settag
        run: echo "image=${{ env.AR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT