name: CI - build & push

on:
  push:
    branches: [ "main", "develop" ]
  pull_request: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: us-central1-docker.pkg.dev
      PROJECT_ID: project-gcp-468607
      REPO_NAME: microrepo
      IMAGE_NAME: sample-app
      FULL_IMAGE_NAME: us-central1-docker.pkg.dev/project-gcp-468607/microrepo/sample-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to GCP (Workload Identity)'
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/237760814620/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@project-gcp-468607.iam.gserviceaccount.com'
          token_format: 'access_token'
          project_id: project-gcp-468607

      - name: Debug all variables
        run: |
          echo "REGISTRY: ${{ env.REGISTRY }}"
          echo "PROJECT_ID: ${{ env.PROJECT_ID }}"  
          echo "REPO_NAME: ${{ env.REPO_NAME }}"
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "FULL_IMAGE_NAME: ${{ env.FULL_IMAGE_NAME }}"
          echo "Github SHA: ${{ github.sha }}"
          echo "Expected tags:"
          echo "  - ${{ env.FULL_IMAGE_NAME }}:${{ github.sha }}"
          echo "  - ${{ env.FULL_IMAGE_NAME }}:latest"

      - name: Login to Artifact Registry (Docker)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.FULL_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.FULL_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.FULL_IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Set image-tag output
        id: settag
        run: echo "image=${{ env.FULL_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Output final image
        run: |
          echo "Successfully built and pushed:"
          echo "${{ env.FULL_IMAGE_NAME }}:${{ github.sha }}"
          echo "${{ env.FULL_IMAGE_NAME }}:latest"